# Generated by Django 6.0 on 2025-12-04 09:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('cafe_literario', 'Café literario'), ('cafe', 'Café'), ('cowork', 'Co-work'), ('otro', 'Otro')], db_index=True, max_length=32)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(db_index=True, max_length=120)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('agregado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares_agregados', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='lugares', to='lugares.etiqueta')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['-agregado_en', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL)),
                ('lugares', models.ManyToManyField(blank=True, related_name='listas', to='lugares.lugar')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('ruido', models.SmallIntegerField(blank=True, help_text='Escala 1-5 o vacío si no aplica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('concurrencia', models.SmallIntegerField(blank=True, help_text='Escala 1-5 o vacío si no aplica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('infraestructura', models.SmallIntegerField(blank=True, help_text='Escala 1-5 o vacío si no aplica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('catalogo', models.SmallIntegerField(blank=True, help_text='Calificación catálogo 1-5; use catalogo_no_aplica para indicar que no aplica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('catalogo_no_aplica', models.BooleanField(default=False, help_text='Marcar si el catálogo no aplica')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='lugares.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='lugar',
            index=models.Index(fields=['tipo'], name='lugares_lug_tipo_30952c_idx'),
        ),
        migrations.AddIndex(
            model_name='lugar',
            index=models.Index(fields=['comuna'], name='lugares_lug_comuna_ba4c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lugar',
            index=models.Index(fields=['agregado_en'], name='lugares_lug_agregad_c4a40c_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['lugar'], name='lugares_res_lugar_i_dc2c53_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['usuario'], name='lugares_res_usuario_fbe165_idx'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['creado_en'], name='lugares_res_creado__ec78f1_idx'),
        ),
    ]
