# Generated by Django 6.0 on 2025-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
