# Generated by Django 6.0 on 2025-12-04 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_lugar_descripcion_lugar_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='catalogo_no_aplica',
        ),
        migrations.AlterField(
            model_name='resena',
            name='catalogo',
            field=models.SmallIntegerField(blank=True, help_text='Calificación catálogo 1-5 o vacío si no aplica', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
